# Generated by Django 5.0 on 2023-12-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='details',
            name='district',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
