# Generated by Django 5.0 on 2023-12-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp2', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Branch',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='country',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
