# Generated by Django 5.0 on 2023-12-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bankapp2', '0005_remove_person_branch_remove_person_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('dob', models.TextField(default=True)),
                ('age', models.IntegerField(default=True)),
                ('gender', models.TextField(default=True)),
                ('phone', models.IntegerField(default=True)),
                ('mail', models.EmailField(default=True, max_length=254)),
                ('address', models.TextField(default=True)),
                ('account', models.TextField(default=True)),
                ('material', models.TextField(default=True)),
                ('branch', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bankapp2.branch')),
                ('district', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bankapp2.district')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp2.district'),
        ),
    ]
